"""empty message

Revision ID: 49fffc49bfe1
Revises: 845a912ccdef
Create Date: 2016-10-31 19:32:12.851049

"""

# revision identifiers, used by Alembic.
revision = '49fffc49bfe1'
down_revision = '845a912ccdef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'user', ['email'], unique=True)
    ### end Alembic commands ###
