"""empty message

Revision ID: 845a912ccdef
Revises: b75660e0f606
Create Date: 2016-10-29 15:24:25.085870

"""

# revision identifiers, used by Alembic.
revision = '845a912ccdef'
down_revision = 'b75660e0f606'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('user', sa.Column('token', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint(None, 'user', ['name'])
    op.drop_column('user', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'token')
    op.drop_column('user', 'name')
    op.drop_column('user', 'last_login_at')
    ### end Alembic commands ###
