"""empty message

Revision ID: 9f3b377c47f1
Revises: 49fffc49bfe1
Create Date: 2016-10-31 23:37:53.663490

"""

# revision identifiers, used by Alembic.
revision = '9f3b377c47f1'
down_revision = '49fffc49bfe1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'user', ['name'], unique=True)
    ### end Alembic commands ###
