"""empty message

Revision ID: b75660e0f606
Revises: None
Create Date: 2016-10-27 23:48:26.364349

"""

# revision identifiers, used by Alembic.
revision = 'b75660e0f606'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ddd', sa.String(length=2), nullable=False),
    sa.Column('number', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_ddd'), 'phone', ['ddd'], unique=True)
    op.create_index(op.f('ix_phone_number'), 'phone', ['number'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_number'), table_name='phone')
    op.drop_index(op.f('ix_phone_ddd'), table_name='phone')
    op.drop_table('phone')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
